# Core Colors
background            #1a110f
foreground            #f1dfda
selection_foreground  #ffb59e
selection_background  #561f0d
cursor                #ffb59e
cursor_text_color     #1a110f

# Regular Colors
color0  #1a110f
color1  #ffb4ab
color2  #ffb59e
color3  #d7c68d
color4  #ffdbd0
color5  #ffdbd0
color6  #e7bdb1
color7  #f1dfda

# Bright Colors
color8  #423734
color9  #ffb4ab
color10 #ffb59e
color11 #d7c68d
color12 #ffdbd0
color13 #ffdbd0 
color14 #e7bdb1
color15 #f1dfda
